long_kernel = false
long_shell = false
theme = "othi"
show = [
  "Host",
  "Kernel",
  "Distribution",
  "OperatingSystem",
  "DesktopEnvironment",
  "WindowManager",
  "Shell",
  "LocalIP",
  "Resolution",
  "Uptime",
  "Processor",
]
